-- Auto-generated from docs/recording-manifest.csv.
-- Do not edit file lists by hand; run tools/generate_manifest.py.
SVS = SVS or {}
SVS.Manifest = {
    ["action_failed"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_ACTION_FAILED_01",
                file = "svs_action_failed_01.ogg",
                subtitle = "Не получилось.",
                direction = "Коротко, без сильной эмоции",
            },
            {
                sound = "SVS_ACTION_FAILED_02",
                file = "svs_action_failed_02.ogg",
                subtitle = "Ещё раз.",
                direction = "Коротко, без сильной эмоции",
            },
            {
                sound = "SVS_ACTION_FAILED_03",
                file = "svs_action_failed_03.ogg",
                subtitle = "Что-то не так.",
                direction = "Коротко, без сильной эмоции",
            },
        },
    },
    ["bitten"] = {
        category = "danger",
        priority = 100,
        cooldown = 90,
        distance = 14,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BITTEN_01",
                file = "svs_bitten_01.ogg",
                subtitle = "Нет... только не это.",
                direction = "Шок, страх, осознание",
            },
            {
                sound = "SVS_BITTEN_02",
                file = "svs_bitten_02.ogg",
                subtitle = "Меня укусили.",
                direction = "Шок, страх, осознание",
            },
            {
                sound = "SVS_BITTEN_03",
                file = "svs_bitten_03.ogg",
                subtitle = "Всё кончено...",
                direction = "Шок, страх, осознание",
            },
        },
    },
    ["bleeding"] = {
        category = "conditions",
        priority = 100,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BLEEDING_01",
                file = "svs_bleeding_01.ogg",
                subtitle = "Я истекаю кровью.",
                direction = "Срочно, болезненно",
            },
            {
                sound = "SVS_BLEEDING_02",
                file = "svs_bleeding_02.ogg",
                subtitle = "Нужно остановить кровь.",
                direction = "Срочно, болезненно",
            },
            {
                sound = "SVS_BLEEDING_03",
                file = "svs_bleeding_03.ogg",
                subtitle = "Кровотечение не прекращается.",
                direction = "Срочно, болезненно",
            },
        },
    },
    ["body_cough_heavy"] = {
        category = "body",
        priority = 100,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BODY_COUGH_HEAVY_01",
                file = "svs_body_cough_heavy_01.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_COUGH_HEAVY_02",
                file = "svs_body_cough_heavy_02.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_COUGH_HEAVY_03",
                file = "svs_body_cough_heavy_03.ogg",
                subtitle = "",
                direction = "Без слов",
            },
        },
    },
    ["body_cough_light"] = {
        category = "body",
        priority = 100,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BODY_COUGH_LIGHT_01",
                file = "svs_body_cough_light_01.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_COUGH_LIGHT_02",
                file = "svs_body_cough_light_02.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_COUGH_LIGHT_03",
                file = "svs_body_cough_light_03.ogg",
                subtitle = "",
                direction = "Без слов",
            },
        },
    },
    ["body_shiver"] = {
        category = "body",
        priority = 60,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BODY_SHIVER_01",
                file = "svs_body_shiver_01.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_SHIVER_02",
                file = "svs_body_shiver_02.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_SHIVER_03",
                file = "svs_body_shiver_03.ogg",
                subtitle = "",
                direction = "Без слов",
            },
        },
    },
    ["body_sneeze"] = {
        category = "body",
        priority = 100,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BODY_SNEEZE_01",
                file = "svs_body_sneeze_01.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_SNEEZE_02",
                file = "svs_body_sneeze_02.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_SNEEZE_03",
                file = "svs_body_sneeze_03.ogg",
                subtitle = "",
                direction = "Без слов",
            },
        },
    },
    ["body_vomit"] = {
        category = "body",
        priority = 60,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BODY_VOMIT_01",
                file = "svs_body_vomit_01.ogg",
                subtitle = "",
                direction = "Без слов; неприятный, но не чрезмерный звук",
            },
            {
                sound = "SVS_BODY_VOMIT_02",
                file = "svs_body_vomit_02.ogg",
                subtitle = "",
                direction = "Без слов; неприятный, но не чрезмерный звук",
            },
            {
                sound = "SVS_BODY_VOMIT_03",
                file = "svs_body_vomit_03.ogg",
                subtitle = "",
                direction = "Без слов; неприятный, но не чрезмерный звук",
            },
        },
    },
    ["body_yawn"] = {
        category = "body",
        priority = 60,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BODY_YAWN_01",
                file = "svs_body_yawn_01.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_YAWN_02",
                file = "svs_body_yawn_02.ogg",
                subtitle = "",
                direction = "Без слов",
            },
            {
                sound = "SVS_BODY_YAWN_03",
                file = "svs_body_yawn_03.ogg",
                subtitle = "",
                direction = "Без слов",
            },
        },
    },
    ["boredom"] = {
        category = "conditions",
        priority = 30,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BOREDOM_01",
                file = "svs_boredom_01.ogg",
                subtitle = "Как же скучно.",
                direction = "Уныло",
            },
            {
                sound = "SVS_BOREDOM_02",
                file = "svs_boredom_02.ogg",
                subtitle = "Тишина сводит с ума.",
                direction = "Уныло",
            },
        },
    },
    ["breath_heavy"] = {
        category = "breathing",
        priority = 100,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BREATH_HEAVY_01",
                file = "svs_breath_heavy_01.ogg",
                subtitle = "",
                direction = "Без слов; крайняя усталость",
            },
            {
                sound = "SVS_BREATH_HEAVY_02",
                file = "svs_breath_heavy_02.ogg",
                subtitle = "",
                direction = "Без слов; крайняя усталость",
            },
            {
                sound = "SVS_BREATH_HEAVY_03",
                file = "svs_breath_heavy_03.ogg",
                subtitle = "",
                direction = "Без слов; крайняя усталость",
            },
        },
    },
    ["breath_light"] = {
        category = "breathing",
        priority = 100,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BREATH_LIGHT_01",
                file = "svs_breath_light_01.ogg",
                subtitle = "",
                direction = "Без слов; после лёгкой нагрузки",
            },
            {
                sound = "SVS_BREATH_LIGHT_02",
                file = "svs_breath_light_02.ogg",
                subtitle = "",
                direction = "Без слов; после лёгкой нагрузки",
            },
            {
                sound = "SVS_BREATH_LIGHT_03",
                file = "svs_breath_light_03.ogg",
                subtitle = "",
                direction = "Без слов; после лёгкой нагрузки",
            },
        },
    },
    ["breath_medium"] = {
        category = "breathing",
        priority = 100,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BREATH_MEDIUM_01",
                file = "svs_breath_medium_01.ogg",
                subtitle = "",
                direction = "Без слов; бег или средняя нагрузка",
            },
            {
                sound = "SVS_BREATH_MEDIUM_02",
                file = "svs_breath_medium_02.ogg",
                subtitle = "",
                direction = "Без слов; бег или средняя нагрузка",
            },
            {
                sound = "SVS_BREATH_MEDIUM_03",
                file = "svs_breath_medium_03.ogg",
                subtitle = "",
                direction = "Без слов; бег или средняя нагрузка",
            },
        },
    },
    ["breath_recover"] = {
        category = "breathing",
        priority = 60,
        cooldown = 12,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BREATH_RECOVER_01",
                file = "svs_breath_recover_01.ogg",
                subtitle = "",
                direction = "Без слов; восстановление после нагрузки",
            },
            {
                sound = "SVS_BREATH_RECOVER_02",
                file = "svs_breath_recover_02.ogg",
                subtitle = "",
                direction = "Без слов; восстановление после нагрузки",
            },
            {
                sound = "SVS_BREATH_RECOVER_03",
                file = "svs_breath_recover_03.ogg",
                subtitle = "",
                direction = "Без слов; восстановление после нагрузки",
            },
        },
    },
    ["build_start"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_BUILD_START_01",
                file = "svs_build_start_01.ogg",
                subtitle = "Начнём строить.",
                direction = "Деловито",
            },
            {
                sound = "SVS_BUILD_START_02",
                file = "svs_build_start_02.ogg",
                subtitle = "Здесь будет надёжнее.",
                direction = "Деловито",
            },
            {
                sound = "SVS_BUILD_START_03",
                file = "svs_build_start_03.ogg",
                subtitle = "Нужно укрепить это место.",
                direction = "Деловито",
            },
        },
    },
    ["call_hey_normal"] = {
        category = "native",
        priority = 100,
        cooldown = 2,
        distance = 18,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_CALL_HEY_NORMAL_01",
                file = "svs_call_hey_normal_01.ogg",
                subtitle = "Эй!",
                direction = "Обычный громкий оклик, без крика",
            },
            {
                sound = "SVS_CALL_HEY_NORMAL_02",
                file = "svs_call_hey_normal_02.ogg",
                subtitle = "Эй, сюда!",
                direction = "Обычный громкий оклик, без крика",
            },
            {
                sound = "SVS_CALL_HEY_NORMAL_03",
                file = "svs_call_hey_normal_03.ogg",
                subtitle = "Сюда!",
                direction = "Обычный громкий оклик, без крика",
            },
        },
    },
    ["call_hey_shout"] = {
        category = "native",
        priority = 100,
        cooldown = 2,
        distance = 22,
        noiseRadius = 18,
        mode = "shout",
        variants = {
            {
                sound = "SVS_CALL_HEY_SHOUT_01",
                file = "svs_call_hey_shout_01.ogg",
                subtitle = "ЭЙ!",
                direction = "Громкий крик на расстояние",
            },
            {
                sound = "SVS_CALL_HEY_SHOUT_02",
                file = "svs_call_hey_shout_02.ogg",
                subtitle = "СЮДА!",
                direction = "Громкий крик на расстояние",
            },
            {
                sound = "SVS_CALL_HEY_SHOUT_03",
                file = "svs_call_hey_shout_03.ogg",
                subtitle = "ЭЙ, Я ЗДЕСЬ!",
                direction = "Громкий крик на расстояние",
            },
        },
    },
    ["call_psst"] = {
        category = "native",
        priority = 100,
        cooldown = 2,
        distance = 6,
        noiseRadius = 0,
        mode = "whisper",
        variants = {
            {
                sound = "SVS_CALL_PSST_01",
                file = "svs_call_psst_01.ogg",
                subtitle = "Пс-с!",
                direction = "Тихий шёпот, близкая дистанция",
            },
            {
                sound = "SVS_CALL_PSST_02",
                file = "svs_call_psst_02.ogg",
                subtitle = "Пс-с-с!",
                direction = "Тихий шёпот, близкая дистанция",
            },
            {
                sound = "SVS_CALL_PSST_03",
                file = "svs_call_psst_03.ogg",
                subtitle = "Эй, тихо!",
                direction = "Тихий шёпот, близкая дистанция",
            },
        },
    },
    ["cold"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COLD_01",
                file = "svs_cold_01.ogg",
                subtitle = "Как же холодно.",
                direction = "Дрожащий голос",
            },
            {
                sound = "SVS_COLD_02",
                file = "svs_cold_02.ogg",
                subtitle = "Я совсем замёрз.",
                direction = "Дрожащий голос",
            },
        },
    },
    ["combat_death"] = {
        category = "combat",
        priority = 100,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_DEATH_01",
                file = "svs_combat_death_01.ogg",
                subtitle = "",
                direction = "Без слов или минимум слов; 1–2 секунды",
            },
            {
                sound = "SVS_COMBAT_DEATH_02",
                file = "svs_combat_death_02.ogg",
                subtitle = "",
                direction = "Без слов или минимум слов; 1–2 секунды",
            },
            {
                sound = "SVS_COMBAT_DEATH_03",
                file = "svs_combat_death_03.ogg",
                subtitle = "",
                direction = "Без слов или минимум слов; 1–2 секунды",
            },
        },
    },
    ["combat_fall"] = {
        category = "combat",
        priority = 60,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_FALL_01",
                file = "svs_combat_fall_01.ogg",
                subtitle = "",
                direction = "Короткая реакция на падение",
            },
            {
                sound = "SVS_COMBAT_FALL_02",
                file = "svs_combat_fall_02.ogg",
                subtitle = "",
                direction = "Короткая реакция на падение",
            },
            {
                sound = "SVS_COMBAT_FALL_03",
                file = "svs_combat_fall_03.ogg",
                subtitle = "",
                direction = "Короткая реакция на падение",
            },
        },
    },
    ["combat_hit_taken_heavy"] = {
        category = "combat",
        priority = 100,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_HIT_TAKEN_HEAVY_01",
                file = "svs_combat_hit_taken_heavy_01.ogg",
                subtitle = "",
                direction = "Сильный урон; не затягивать",
            },
            {
                sound = "SVS_COMBAT_HIT_TAKEN_HEAVY_02",
                file = "svs_combat_hit_taken_heavy_02.ogg",
                subtitle = "А-а-а!",
                direction = "Сильный урон; не затягивать",
            },
            {
                sound = "SVS_COMBAT_HIT_TAKEN_HEAVY_03",
                file = "svs_combat_hit_taken_heavy_03.ogg",
                subtitle = "Твою мать!",
                direction = "Сильный урон; не затягивать",
            },
        },
    },
    ["combat_hit_taken_light"] = {
        category = "combat",
        priority = 100,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_HIT_TAKEN_LIGHT_01",
                file = "svs_combat_hit_taken_light_01.ogg",
                subtitle = "",
                direction = "Небольшой урон",
            },
            {
                sound = "SVS_COMBAT_HIT_TAKEN_LIGHT_02",
                file = "svs_combat_hit_taken_light_02.ogg",
                subtitle = "",
                direction = "Небольшой урон",
            },
            {
                sound = "SVS_COMBAT_HIT_TAKEN_LIGHT_03",
                file = "svs_combat_hit_taken_light_03.ogg",
                subtitle = "",
                direction = "Небольшой урон",
            },
        },
    },
    ["combat_hit_taken_medium"] = {
        category = "combat",
        priority = 100,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_HIT_TAKEN_MEDIUM_01",
                file = "svs_combat_hit_taken_medium_01.ogg",
                subtitle = "",
                direction = "Средний урон",
            },
            {
                sound = "SVS_COMBAT_HIT_TAKEN_MEDIUM_02",
                file = "svs_combat_hit_taken_medium_02.ogg",
                subtitle = "Чёрт!",
                direction = "Средний урон",
            },
            {
                sound = "SVS_COMBAT_HIT_TAKEN_MEDIUM_03",
                file = "svs_combat_hit_taken_medium_03.ogg",
                subtitle = "Ай, больно!",
                direction = "Средний урон",
            },
        },
    },
    ["combat_shove"] = {
        category = "combat",
        priority = 100,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_SHOVE_01",
                file = "svs_combat_shove_01.ogg",
                subtitle = "",
                direction = "Резко и коротко",
            },
            {
                sound = "SVS_COMBAT_SHOVE_02",
                file = "svs_combat_shove_02.ogg",
                subtitle = "",
                direction = "Резко и коротко",
            },
            {
                sound = "SVS_COMBAT_SHOVE_03",
                file = "svs_combat_shove_03.ogg",
                subtitle = "",
                direction = "Резко и коротко",
            },
        },
    },
    ["combat_stomp"] = {
        category = "combat",
        priority = 60,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_STOMP_01",
                file = "svs_combat_stomp_01.ogg",
                subtitle = "",
                direction = "Резко, без длинной фразы",
            },
            {
                sound = "SVS_COMBAT_STOMP_02",
                file = "svs_combat_stomp_02.ogg",
                subtitle = "",
                direction = "Резко, без длинной фразы",
            },
            {
                sound = "SVS_COMBAT_STOMP_03",
                file = "svs_combat_stomp_03.ogg",
                subtitle = "",
                direction = "Резко, без длинной фразы",
            },
        },
    },
    ["combat_swing_heavy"] = {
        category = "combat",
        priority = 100,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_SWING_HEAVY_01",
                file = "svs_combat_swing_heavy_01.ogg",
                subtitle = "",
                direction = "Коротко; тяжёлый удар",
            },
            {
                sound = "SVS_COMBAT_SWING_HEAVY_02",
                file = "svs_combat_swing_heavy_02.ogg",
                subtitle = "",
                direction = "Коротко; тяжёлый удар",
            },
            {
                sound = "SVS_COMBAT_SWING_HEAVY_03",
                file = "svs_combat_swing_heavy_03.ogg",
                subtitle = "",
                direction = "Коротко; тяжёлый удар",
            },
        },
    },
    ["combat_swing_light"] = {
        category = "combat",
        priority = 100,
        cooldown = 3,
        distance = 12,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COMBAT_SWING_LIGHT_01",
                file = "svs_combat_swing_light_01.ogg",
                subtitle = "",
                direction = "Очень коротко; лёгкий удар",
            },
            {
                sound = "SVS_COMBAT_SWING_LIGHT_02",
                file = "svs_combat_swing_light_02.ogg",
                subtitle = "",
                direction = "Очень коротко; лёгкий удар",
            },
            {
                sound = "SVS_COMBAT_SWING_LIGHT_03",
                file = "svs_combat_swing_light_03.ogg",
                subtitle = "",
                direction = "Очень коротко; лёгкий удар",
            },
        },
    },
    ["cooking_start"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_COOKING_START_01",
                file = "svs_cooking_start_01.ogg",
                subtitle = "Нужно что-нибудь приготовить.",
                direction = "Спокойно",
            },
            {
                sound = "SVS_COOKING_START_02",
                file = "svs_cooking_start_02.ogg",
                subtitle = "Наконец-то нормальная еда.",
                direction = "Спокойно",
            },
            {
                sound = "SVS_COOKING_START_03",
                file = "svs_cooking_start_03.ogg",
                subtitle = "Посмотрим, что получится.",
                direction = "Спокойно",
            },
        },
    },
    ["craft_start"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_CRAFT_START_01",
                file = "svs_craft_start_01.ogg",
                subtitle = "Приступим.",
                direction = "Спокойно",
            },
            {
                sound = "SVS_CRAFT_START_02",
                file = "svs_craft_start_02.ogg",
                subtitle = "Нужно сделать всё аккуратно.",
                direction = "Спокойно",
            },
            {
                sound = "SVS_CRAFT_START_03",
                file = "svs_craft_start_03.ogg",
                subtitle = "Посмотрим, сработает ли.",
                direction = "Спокойно",
            },
        },
    },
    ["danger_close"] = {
        category = "danger",
        priority = 60,
        cooldown = 90,
        distance = 22,
        noiseRadius = 18,
        mode = "shout",
        variants = {
            {
                sound = "SVS_DANGER_CLOSE_01",
                file = "svs_danger_close_01.ogg",
                subtitle = "Слишком близко!",
                direction = "Резко и срочно",
            },
            {
                sound = "SVS_DANGER_CLOSE_02",
                file = "svs_danger_close_02.ogg",
                subtitle = "Назад!",
                direction = "Резко и срочно",
            },
            {
                sound = "SVS_DANGER_CLOSE_03",
                file = "svs_danger_close_03.ogg",
                subtitle = "Убирайся от меня!",
                direction = "Резко и срочно",
            },
        },
    },
    ["door_breaking"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_DOOR_BREAKING_01",
                file = "svs_door_breaking_01.ogg",
                subtitle = "Сейчас откроем.",
                direction = "Решительно",
            },
            {
                sound = "SVS_DOOR_BREAKING_02",
                file = "svs_door_breaking_02.ogg",
                subtitle = "Отойди от двери.",
                direction = "Решительно",
            },
            {
                sound = "SVS_DOOR_BREAKING_03",
                file = "svs_door_breaking_03.ogg",
                subtitle = "Придётся ломать.",
                direction = "Решительно",
            },
        },
    },
    ["door_locked"] = {
        category = "actions",
        priority = 60,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_DOOR_LOCKED_01",
                file = "svs_door_locked_01.ogg",
                subtitle = "Заперто.",
                direction = "Спокойно, раздражённо",
            },
            {
                sound = "SVS_DOOR_LOCKED_02",
                file = "svs_door_locked_02.ogg",
                subtitle = "Дверь закрыта.",
                direction = "Спокойно, раздражённо",
            },
            {
                sound = "SVS_DOOR_LOCKED_03",
                file = "svs_door_locked_03.ogg",
                subtitle = "Придётся искать другой вход.",
                direction = "Спокойно, раздражённо",
            },
        },
    },
    ["encumbered_heavy"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_ENCUMBERED_HEAVY_01",
                file = "svs_encumbered_heavy_01.ogg",
                subtitle = "Я это не унесу.",
                direction = "Сильная нагрузка",
            },
            {
                sound = "SVS_ENCUMBERED_HEAVY_02",
                file = "svs_encumbered_heavy_02.ogg",
                subtitle = "Нужно что-то выбросить.",
                direction = "Сильная нагрузка",
            },
        },
    },
    ["encumbered_light"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_ENCUMBERED_LIGHT_01",
                file = "svs_encumbered_light_01.ogg",
                subtitle = "Тяжеловато.",
                direction = "Небольшая нагрузка",
            },
            {
                sound = "SVS_ENCUMBERED_LIGHT_02",
                file = "svs_encumbered_light_02.ogg",
                subtitle = "Я набрал слишком много.",
                direction = "Небольшая нагрузка",
            },
        },
    },
    ["enter_vehicle"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_ENTER_VEHICLE_01",
                file = "svs_enter_vehicle_01.ogg",
                subtitle = "Поехали.",
                direction = "Коротко",
            },
            {
                sound = "SVS_ENTER_VEHICLE_02",
                file = "svs_enter_vehicle_02.ogg",
                subtitle = "Надеюсь, заведётся.",
                direction = "Коротко",
            },
            {
                sound = "SVS_ENTER_VEHICLE_03",
                file = "svs_enter_vehicle_03.ogg",
                subtitle = "Давай, не подведи.",
                direction = "Коротко",
            },
        },
    },
    ["fatigue_heavy"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_FATIGUE_HEAVY_01",
                file = "svs_fatigue_heavy_01.ogg",
                subtitle = "Я еле держусь на ногах.",
                direction = "Сильная усталость",
            },
            {
                sound = "SVS_FATIGUE_HEAVY_02",
                file = "svs_fatigue_heavy_02.ogg",
                subtitle = "Нужно поспать, прямо сейчас.",
                direction = "Сильная усталость",
            },
        },
    },
    ["fatigue_light"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_FATIGUE_LIGHT_01",
                file = "svs_fatigue_light_01.ogg",
                subtitle = "Я устал.",
                direction = "Небольшая усталость",
            },
            {
                sound = "SVS_FATIGUE_LIGHT_02",
                file = "svs_fatigue_light_02.ogg",
                subtitle = "Нужно немного отдохнуть.",
                direction = "Небольшая усталость",
            },
        },
    },
    ["heat"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_HEAT_01",
                file = "svs_heat_01.ogg",
                subtitle = "Слишком жарко.",
                direction = "Усталость от жары",
            },
            {
                sound = "SVS_HEAT_02",
                file = "svs_heat_02.ogg",
                subtitle = "Я сейчас сварюсь.",
                direction = "Усталость от жары",
            },
        },
    },
    ["hunger_heavy"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_HUNGER_HEAVY_01",
                file = "svs_hunger_heavy_01.ogg",
                subtitle = "Я умираю с голоду.",
                direction = "Сильный голод",
            },
            {
                sound = "SVS_HUNGER_HEAVY_02",
                file = "svs_hunger_heavy_02.ogg",
                subtitle = "Нужно срочно найти еду.",
                direction = "Сильный голод",
            },
        },
    },
    ["hunger_light"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_HUNGER_LIGHT_01",
                file = "svs_hunger_light_01.ogg",
                subtitle = "Неплохо бы перекусить.",
                direction = "Лёгкий голод",
            },
            {
                sound = "SVS_HUNGER_LIGHT_02",
                file = "svs_hunger_light_02.ogg",
                subtitle = "Я начинаю хотеть есть.",
                direction = "Лёгкий голод",
            },
        },
    },
    ["item_broken"] = {
        category = "actions",
        priority = 60,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_ITEM_BROKEN_01",
                file = "svs_item_broken_01.ogg",
                subtitle = "Чёрт, сломалось.",
                direction = "Раздражённо",
            },
            {
                sound = "SVS_ITEM_BROKEN_02",
                file = "svs_item_broken_02.ogg",
                subtitle = "Вот и всё.",
                direction = "Раздражённо",
            },
            {
                sound = "SVS_ITEM_BROKEN_03",
                file = "svs_item_broken_03.ogg",
                subtitle = "Нужно найти замену.",
                direction = "Раздражённо",
            },
        },
    },
    ["megaphone_hey"] = {
        category = "native",
        priority = 60,
        cooldown = 2,
        distance = 36,
        noiseRadius = 30,
        mode = "megaphone",
        variants = {
            {
                sound = "SVS_MEGAPHONE_HEY_01",
                file = "svs_megaphone_hey_01.ogg",
                subtitle = "ЭЙ!",
                direction = "Громко и чётко; эффект мегафона добавит мод",
            },
            {
                sound = "SVS_MEGAPHONE_HEY_02",
                file = "svs_megaphone_hey_02.ogg",
                subtitle = "СЮДА!",
                direction = "Громко и чётко; эффект мегафона добавит мод",
            },
            {
                sound = "SVS_MEGAPHONE_HEY_03",
                file = "svs_megaphone_hey_03.ogg",
                subtitle = "Я ЗДЕСЬ!",
                direction = "Громко и чётко; эффект мегафона добавит мод",
            },
        },
    },
    ["megaphone_psst"] = {
        category = "native",
        priority = 60,
        cooldown = 2,
        distance = 6,
        noiseRadius = 0,
        mode = "whisper",
        variants = {
            {
                sound = "SVS_MEGAPHONE_PSST_01",
                file = "svs_megaphone_psst_01.ogg",
                subtitle = "ПС-С!",
                direction = "Громко и чётко; без самостоятельного эффекта",
            },
            {
                sound = "SVS_MEGAPHONE_PSST_02",
                file = "svs_megaphone_psst_02.ogg",
                subtitle = "ЭЙ, СЮДА!",
                direction = "Громко и чётко; без самостоятельного эффекта",
            },
            {
                sound = "SVS_MEGAPHONE_PSST_03",
                file = "svs_megaphone_psst_03.ogg",
                subtitle = "СЛЫШИШЬ МЕНЯ?",
                direction = "Громко и чётко; без самостоятельного эффекта",
            },
        },
    },
    ["mp_ammo"] = {
        category = "multiplayer",
        priority = 30,
        cooldown = 4,
        distance = 18,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_MP_AMMO_01",
                file = "svs_mp_ammo_01.ogg",
                subtitle = "У меня мало патронов.",
                direction = "Коротко",
            },
            {
                sound = "SVS_MP_AMMO_02",
                file = "svs_mp_ammo_02.ogg",
                subtitle = "Боеприпасы заканчиваются.",
                direction = "Коротко",
            },
            {
                sound = "SVS_MP_AMMO_03",
                file = "svs_mp_ammo_03.ogg",
                subtitle = "Нужны патроны.",
                direction = "Коротко",
            },
        },
    },
    ["mp_clear"] = {
        category = "multiplayer",
        priority = 30,
        cooldown = 4,
        distance = 18,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_MP_CLEAR_01",
                file = "svs_mp_clear_01.ogg",
                subtitle = "Чисто.",
                direction = "Спокойно",
            },
            {
                sound = "SVS_MP_CLEAR_02",
                file = "svs_mp_clear_02.ogg",
                subtitle = "Здесь безопасно.",
                direction = "Спокойно",
            },
            {
                sound = "SVS_MP_CLEAR_03",
                file = "svs_mp_clear_03.ogg",
                subtitle = "Можно идти.",
                direction = "Спокойно",
            },
        },
    },
    ["mp_follow"] = {
        category = "multiplayer",
        priority = 30,
        cooldown = 4,
        distance = 18,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_MP_FOLLOW_01",
                file = "svs_mp_follow_01.ogg",
                subtitle = "За мной.",
                direction = "Командно, но спокойно",
            },
            {
                sound = "SVS_MP_FOLLOW_02",
                file = "svs_mp_follow_02.ogg",
                subtitle = "Идём вместе.",
                direction = "Командно, но спокойно",
            },
            {
                sound = "SVS_MP_FOLLOW_03",
                file = "svs_mp_follow_03.ogg",
                subtitle = "Не отставай.",
                direction = "Командно, но спокойно",
            },
        },
    },
    ["mp_help"] = {
        category = "multiplayer",
        priority = 60,
        cooldown = 4,
        distance = 22,
        noiseRadius = 18,
        mode = "shout",
        variants = {
            {
                sound = "SVS_MP_HELP_01",
                file = "svs_mp_help_01.ogg",
                subtitle = "Помогите!",
                direction = "Громко и срочно",
            },
            {
                sound = "SVS_MP_HELP_02",
                file = "svs_mp_help_02.ogg",
                subtitle = "Мне нужна помощь!",
                direction = "Громко и срочно",
            },
            {
                sound = "SVS_MP_HELP_03",
                file = "svs_mp_help_03.ogg",
                subtitle = "Сюда, быстро!",
                direction = "Громко и срочно",
            },
        },
    },
    ["mp_retreat"] = {
        category = "multiplayer",
        priority = 60,
        cooldown = 4,
        distance = 22,
        noiseRadius = 18,
        mode = "shout",
        variants = {
            {
                sound = "SVS_MP_RETREAT_01",
                file = "svs_mp_retreat_01.ogg",
                subtitle = "Отходим!",
                direction = "Командный крик",
            },
            {
                sound = "SVS_MP_RETREAT_02",
                file = "svs_mp_retreat_02.ogg",
                subtitle = "Назад!",
                direction = "Командный крик",
            },
            {
                sound = "SVS_MP_RETREAT_03",
                file = "svs_mp_retreat_03.ogg",
                subtitle = "Уходим отсюда!",
                direction = "Командный крик",
            },
        },
    },
    ["mp_stop"] = {
        category = "multiplayer",
        priority = 30,
        cooldown = 4,
        distance = 18,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_MP_STOP_01",
                file = "svs_mp_stop_01.ogg",
                subtitle = "Стой.",
                direction = "Чётко и коротко",
            },
            {
                sound = "SVS_MP_STOP_02",
                file = "svs_mp_stop_02.ogg",
                subtitle = "Остановись.",
                direction = "Чётко и коротко",
            },
            {
                sound = "SVS_MP_STOP_03",
                file = "svs_mp_stop_03.ogg",
                subtitle = "Не двигайся.",
                direction = "Чётко и коротко",
            },
        },
    },
    ["mp_warning"] = {
        category = "multiplayer",
        priority = 60,
        cooldown = 4,
        distance = 22,
        noiseRadius = 18,
        mode = "shout",
        variants = {
            {
                sound = "SVS_MP_WARNING_01",
                file = "svs_mp_warning_01.ogg",
                subtitle = "Осторожно!",
                direction = "Резко и громко",
            },
            {
                sound = "SVS_MP_WARNING_02",
                file = "svs_mp_warning_02.ogg",
                subtitle = "Сзади!",
                direction = "Резко и громко",
            },
            {
                sound = "SVS_MP_WARNING_03",
                file = "svs_mp_warning_03.ogg",
                subtitle = "Берегись!",
                direction = "Резко и громко",
            },
        },
    },
    ["night_started"] = {
        category = "world",
        priority = 30,
        cooldown = 300,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_NIGHT_STARTED_01",
                file = "svs_night_started_01.ogg",
                subtitle = "Скоро совсем стемнеет.",
                direction = "Тихое предупреждение самому себе",
            },
            {
                sound = "SVS_NIGHT_STARTED_02",
                file = "svs_night_started_02.ogg",
                subtitle = "Ночь близко.",
                direction = "Тихое предупреждение самому себе",
            },
            {
                sound = "SVS_NIGHT_STARTED_03",
                file = "svs_night_started_03.ogg",
                subtitle = "Лучше не оставаться снаружи.",
                direction = "Тихое предупреждение самому себе",
            },
        },
    },
    ["other_player_spotted"] = {
        category = "world",
        priority = 60,
        cooldown = 300,
        distance = 22,
        noiseRadius = 18,
        mode = "shout",
        variants = {
            {
                sound = "SVS_OTHER_PLAYER_SPOTTED_01",
                file = "svs_other_player_spotted_01.ogg",
                subtitle = "Эй, человек!",
                direction = "Громко, но не агрессивно",
            },
            {
                sound = "SVS_OTHER_PLAYER_SPOTTED_02",
                file = "svs_other_player_spotted_02.ogg",
                subtitle = "Я не заражён!",
                direction = "Громко, но не агрессивно",
            },
            {
                sound = "SVS_OTHER_PLAYER_SPOTTED_03",
                file = "svs_other_player_spotted_03.ogg",
                subtitle = "Стой, я свой!",
                direction = "Громко, но не агрессивно",
            },
        },
    },
    ["pain_heavy"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_PAIN_HEAVY_01",
                file = "svs_pain_heavy_01.ogg",
                subtitle = "Боль становится сильнее.",
                direction = "Сильная боль",
            },
            {
                sound = "SVS_PAIN_HEAVY_02",
                file = "svs_pain_heavy_02.ogg",
                subtitle = "Я так долго не протяну.",
                direction = "Сильная боль",
            },
        },
    },
    ["pain_light"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_PAIN_LIGHT_01",
                file = "svs_pain_light_01.ogg",
                subtitle = "Побаливает.",
                direction = "Лёгкая боль",
            },
            {
                sound = "SVS_PAIN_LIGHT_02",
                file = "svs_pain_light_02.ogg",
                subtitle = "Ничего, переживу.",
                direction = "Лёгкая боль",
            },
        },
    },
    ["panic_heavy"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_PANIC_HEAVY_01",
                file = "svs_panic_heavy_01.ogg",
                subtitle = "Я не справлюсь!",
                direction = "Сильная паника",
            },
            {
                sound = "SVS_PANIC_HEAVY_02",
                file = "svs_panic_heavy_02.ogg",
                subtitle = "Нужно уходить отсюда!",
                direction = "Сильная паника",
            },
        },
    },
    ["panic_light"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_PANIC_LIGHT_01",
                file = "svs_panic_light_01.ogg",
                subtitle = "Спокойно... спокойно.",
                direction = "Сдерживаемая паника",
            },
            {
                sound = "SVS_PANIC_LIGHT_02",
                file = "svs_panic_light_02.ogg",
                subtitle = "Нужно собраться.",
                direction = "Сдерживаемая паника",
            },
        },
    },
    ["rare_item_found"] = {
        category = "world",
        priority = 30,
        cooldown = 300,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_RARE_ITEM_FOUND_01",
                file = "svs_rare_item_found_01.ogg",
                subtitle = "Вот это удача.",
                direction = "Сдержанная радость",
            },
            {
                sound = "SVS_RARE_ITEM_FOUND_02",
                file = "svs_rare_item_found_02.ogg",
                subtitle = "Наконец-то что-то полезное.",
                direction = "Сдержанная радость",
            },
            {
                sound = "SVS_RARE_ITEM_FOUND_03",
                file = "svs_rare_item_found_03.ogg",
                subtitle = "Отличная находка.",
                direction = "Сдержанная радость",
            },
        },
    },
    ["reading_start"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_READING_START_01",
                file = "svs_reading_start_01.ogg",
                subtitle = "Посмотрим, что здесь написано.",
                direction = "Тихо, спокойно",
            },
            {
                sound = "SVS_READING_START_02",
                file = "svs_reading_start_02.ogg",
                subtitle = "Нужно разобраться.",
                direction = "Тихо, спокойно",
            },
            {
                sound = "SVS_READING_START_03",
                file = "svs_reading_start_03.ogg",
                subtitle = "Может, узнаю что-то полезное.",
                direction = "Тихо, спокойно",
            },
        },
    },
    ["reload_start"] = {
        category = "actions",
        priority = 60,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_RELOAD_START_01",
                file = "svs_reload_start_01.ogg",
                subtitle = "Перезаряжаюсь.",
                direction = "Коротко; третья фраза громче",
            },
            {
                sound = "SVS_RELOAD_START_02",
                file = "svs_reload_start_02.ogg",
                subtitle = "Нужен новый магазин.",
                direction = "Коротко; третья фраза громче",
            },
            {
                sound = "SVS_RELOAD_START_03",
                file = "svs_reload_start_03.ogg",
                subtitle = "Прикройте, перезарядка!",
                direction = "Коротко; третья фраза громче",
            },
        },
    },
    ["sadness"] = {
        category = "conditions",
        priority = 30,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_SADNESS_01",
                file = "svs_sadness_01.ogg",
                subtitle = "Всё это бессмысленно.",
                direction = "Подавленно, без переигрывания",
            },
            {
                sound = "SVS_SADNESS_02",
                file = "svs_sadness_02.ogg",
                subtitle = "Я больше так не могу.",
                direction = "Подавленно, без переигрывания",
            },
        },
    },
    ["safe_relief"] = {
        category = "world",
        priority = 60,
        cooldown = 300,
        distance = 6,
        noiseRadius = 0,
        mode = "whisper",
        variants = {
            {
                sound = "SVS_SAFE_RELIEF_01",
                file = "svs_safe_relief_01.ogg",
                subtitle = "Кажется, оторвался.",
                direction = "Облегчение после опасности",
            },
            {
                sound = "SVS_SAFE_RELIEF_02",
                file = "svs_safe_relief_02.ogg",
                subtitle = "Пока безопасно.",
                direction = "Облегчение после опасности",
            },
            {
                sound = "SVS_SAFE_RELIEF_03",
                file = "svs_safe_relief_03.ogg",
                subtitle = "Можно перевести дух.",
                direction = "Облегчение после опасности",
            },
        },
    },
    ["sickness_heavy"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_SICKNESS_HEAVY_01",
                file = "svs_sickness_heavy_01.ogg",
                subtitle = "Мне становится хуже.",
                direction = "Сильная болезнь",
            },
            {
                sound = "SVS_SICKNESS_HEAVY_02",
                file = "svs_sickness_heavy_02.ogg",
                subtitle = "Я серьёзно болен.",
                direction = "Сильная болезнь",
            },
        },
    },
    ["sickness_light"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_SICKNESS_LIGHT_01",
                file = "svs_sickness_light_01.ogg",
                subtitle = "Кажется, я заболеваю.",
                direction = "Недомогание",
            },
            {
                sound = "SVS_SICKNESS_LIGHT_02",
                file = "svs_sickness_light_02.ogg",
                subtitle = "Мне нехорошо.",
                direction = "Недомогание",
            },
        },
    },
    ["suspicious_noise"] = {
        category = "danger",
        priority = 60,
        cooldown = 90,
        distance = 6,
        noiseRadius = 0,
        mode = "whisper",
        variants = {
            {
                sound = "SVS_SUSPICIOUS_NOISE_01",
                file = "svs_suspicious_noise_01.ogg",
                subtitle = "Что это было?",
                direction = "Тихо, настороженно",
            },
            {
                sound = "SVS_SUSPICIOUS_NOISE_02",
                file = "svs_suspicious_noise_02.ogg",
                subtitle = "Я что-то слышал.",
                direction = "Тихо, настороженно",
            },
            {
                sound = "SVS_SUSPICIOUS_NOISE_03",
                file = "svs_suspicious_noise_03.ogg",
                subtitle = "Там кто-то есть.",
                direction = "Тихо, настороженно",
            },
        },
    },
    ["thirst_heavy"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_THIRST_HEAVY_01",
                file = "svs_thirst_heavy_01.ogg",
                subtitle = "Горло совсем пересохло.",
                direction = "Сильная жажда",
            },
            {
                sound = "SVS_THIRST_HEAVY_02",
                file = "svs_thirst_heavy_02.ogg",
                subtitle = "Мне срочно нужна вода.",
                direction = "Сильная жажда",
            },
        },
    },
    ["thirst_light"] = {
        category = "conditions",
        priority = 60,
        cooldown = 360,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_THIRST_LIGHT_01",
                file = "svs_thirst_light_01.ogg",
                subtitle = "Хочется пить.",
                direction = "Лёгкая жажда",
            },
            {
                sound = "SVS_THIRST_LIGHT_02",
                file = "svs_thirst_light_02.ogg",
                subtitle = "Нужна вода.",
                direction = "Лёгкая жажда",
            },
        },
    },
    ["treatment_start"] = {
        category = "actions",
        priority = 60,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_TREATMENT_START_01",
                file = "svs_treatment_start_01.ogg",
                subtitle = "Нужно обработать рану.",
                direction = "Сосредоточенно",
            },
            {
                sound = "SVS_TREATMENT_START_02",
                file = "svs_treatment_start_02.ogg",
                subtitle = "Сначала остановить кровь.",
                direction = "Сосредоточенно",
            },
            {
                sound = "SVS_TREATMENT_START_03",
                file = "svs_treatment_start_03.ogg",
                subtitle = "Потерпи, сейчас перевяжу.",
                direction = "Сосредоточенно",
            },
        },
    },
    ["vehicle_repair"] = {
        category = "actions",
        priority = 30,
        cooldown = 45,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_VEHICLE_REPAIR_01",
                file = "svs_vehicle_repair_01.ogg",
                subtitle = "Попробую починить.",
                direction = "Сосредоточенно",
            },
            {
                sound = "SVS_VEHICLE_REPAIR_02",
                file = "svs_vehicle_repair_02.ogg",
                subtitle = "Похоже, проблема здесь.",
                direction = "Сосредоточенно",
            },
            {
                sound = "SVS_VEHICLE_REPAIR_03",
                file = "svs_vehicle_repair_03.ogg",
                subtitle = "Эта развалюха ещё поедет.",
                direction = "Сосредоточенно",
            },
        },
    },
    ["weather_bad"] = {
        category = "world",
        priority = 30,
        cooldown = 300,
        distance = 8,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_WEATHER_BAD_01",
                file = "svs_weather_bad_01.ogg",
                subtitle = "Погода портится.",
                direction = "Спокойно и обеспокоенно",
            },
            {
                sound = "SVS_WEATHER_BAD_02",
                file = "svs_weather_bad_02.ogg",
                subtitle = "Нужно искать укрытие.",
                direction = "Спокойно и обеспокоенно",
            },
            {
                sound = "SVS_WEATHER_BAD_03",
                file = "svs_weather_bad_03.ogg",
                subtitle = "Не нравится мне это небо.",
                direction = "Спокойно и обеспокоенно",
            },
        },
    },
    ["zombie_killed"] = {
        category = "danger",
        priority = 30,
        cooldown = 90,
        distance = 14,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_ZOMBIE_KILLED_01",
                file = "svs_zombie_killed_01.ogg",
                subtitle = "Готов.",
                direction = "Коротко, после убийства",
            },
            {
                sound = "SVS_ZOMBIE_KILLED_02",
                file = "svs_zombie_killed_02.ogg",
                subtitle = "Минус один.",
                direction = "Коротко, после убийства",
            },
            {
                sound = "SVS_ZOMBIE_KILLED_03",
                file = "svs_zombie_killed_03.ogg",
                subtitle = "Больше не встанет.",
                direction = "Коротко, после убийства",
            },
        },
    },
    ["zombie_spotted_horde"] = {
        category = "danger",
        priority = 100,
        cooldown = 90,
        distance = 22,
        noiseRadius = 18,
        mode = "shout",
        variants = {
            {
                sound = "SVS_ZOMBIE_SPOTTED_HORDE_01",
                file = "svs_zombie_spotted_horde_01.ogg",
                subtitle = "Там целая орда!",
                direction = "Испуганно и срочно",
            },
            {
                sound = "SVS_ZOMBIE_SPOTTED_HORDE_02",
                file = "svs_zombie_spotted_horde_02.ogg",
                subtitle = "Их слишком много!",
                direction = "Испуганно и срочно",
            },
            {
                sound = "SVS_ZOMBIE_SPOTTED_HORDE_03",
                file = "svs_zombie_spotted_horde_03.ogg",
                subtitle = "Назад, быстро!",
                direction = "Испуганно и срочно",
            },
        },
    },
    ["zombie_spotted_medium"] = {
        category = "danger",
        priority = 60,
        cooldown = 90,
        distance = 14,
        noiseRadius = 0,
        mode = "normal",
        variants = {
            {
                sound = "SVS_ZOMBIE_SPOTTED_MEDIUM_01",
                file = "svs_zombie_spotted_medium_01.ogg",
                subtitle = "Их несколько.",
                direction = "Напряжённо, но без паники",
            },
            {
                sound = "SVS_ZOMBIE_SPOTTED_MEDIUM_02",
                file = "svs_zombie_spotted_medium_02.ogg",
                subtitle = "Плохо дело.",
                direction = "Напряжённо, но без паники",
            },
            {
                sound = "SVS_ZOMBIE_SPOTTED_MEDIUM_03",
                file = "svs_zombie_spotted_medium_03.ogg",
                subtitle = "Нужно быть осторожнее.",
                direction = "Напряжённо, но без паники",
            },
        },
    },
    ["zombie_spotted_small"] = {
        category = "danger",
        priority = 60,
        cooldown = 90,
        distance = 6,
        noiseRadius = 0,
        mode = "whisper",
        variants = {
            {
                sound = "SVS_ZOMBIE_SPOTTED_SMALL_01",
                file = "svs_zombie_spotted_small_01.ogg",
                subtitle = "Зомби.",
                direction = "Тихо и настороженно",
            },
            {
                sound = "SVS_ZOMBIE_SPOTTED_SMALL_02",
                file = "svs_zombie_spotted_small_02.ogg",
                subtitle = "Один мертвяк.",
                direction = "Тихо и настороженно",
            },
            {
                sound = "SVS_ZOMBIE_SPOTTED_SMALL_03",
                file = "svs_zombie_spotted_small_03.ogg",
                subtitle = "Вижу заражённого.",
                direction = "Тихо и настороженно",
            },
        },
    },
}

function SVS.GetManifestEntry(key)
    if type(key) ~= "string" then return nil end
    return SVS.Manifest[key]
end

function SVS.IsKnownEvent(key)
    return SVS.GetManifestEntry(key) ~= nil
end
